### ISSUE TITLE
arbitrary qemu flags

### ISSUE THREAD

**Issue by trombik** [esmil/kitchen-qemu#7]
`image` is a convenient way to boot simple setup, but sometimes, you need more controls. the current implementation hard-codes `qemu` flags and whenever you need unsupported flags, you need to add the flag to the code. in some cases, `virtio-scsi-pci`, which is enforced by `kitchen-qemu`, cannot be used.

how about providing something like `flags`? `flags` would just pass all its values to `qemu`.

```yaml
driver:
  name: qemu

platforms:
  - name: jessie
    driver:
      flags:
        serial: stdio
        machine: versatilepb
        cpu: arm1176
        drive: if=scsi,id=drive0,snapshot=on,file=image.qcow2
        kernel: kernel
        append: "root=/dev/sda2 rootfstype=ext4 rw console=ttyAMA0 console=ttyS0"
        m: 256
```

**Comment by esmil** [comment]
Hi Trombik,

Yes, I very much agree that hardcoding virtio-scsi-pci is stupid. In fact you can see in the git log that I've gone from very specific options to more free-form options as I've added options to kitchen-qemu. The latest "networks" addition lets you specify almost any -netdev and -device parameters you want.

However I can see a few problems with your flags suggestion:

1)  You can't specify the same parameter multiple times. Eg. this won't work
```yaml
driver:
  name: qemu

platforms:
  - name: jessie
    driver:
      flags:
        serial: stdio
        machine: versatilepb
        cpu: arm1176
        device: "virtio-scsi-device,id=scsi"
        device: "scsi-hd,drive=drive0"
        drive: "if=none,id=drive0,snapshot=on,file=image1.qcow2"
        device: "scsi-hd,drive=drive1"
        drive: "if=none,id=drive1,snapshot=off,file=image2.qcow2"
        kernel: kernel
        append: "root=/dev/sda2 rootfstype=ext4 rw console=ttyAMA0 console=ttyS0"
        m: 256
```

2) The order of the parameters is important to qemu and even if ruby's yaml/json parser somehow
  preservers the order from the `.kitchen.yml` file to the hash's .each iterator I really don't think we
  should rely on it.

Both problems above could be fixed my making flags an array of hashes like so:
```yaml
driver:
  name: qemu

platforms:
  - name: jessie
    driver:
      flags:
        - serial: stdio
        - machine: versatilepb
        - cpu: arm1176
        - device: "virtio-scsi-device,id=scsi"
        - device: "scsi-hd,drive=drive0"
        - drive: "if=none,id=drive0,snapshot=on,file=image1.qcow2"
        - device: "scsi-hd,drive=drive1"
        - drive: "if=none,id=drive1,snapshot=off,file=image2.qcow2"
        - kernel: kernel
        - append: "root=/dev/sda2 rootfstype=ext4 rw console=ttyAMA0 console=ttyS0"
        - m: 256
```
  ..but this leads us the the question of

3)  How should the defaults interact with the flags setting? Should all defaults be disabled when the user
  specifies some flags or should every default iterate the flags array to see if it has an overriding option?
  At least the `-chardev` and `-mon` options should probably always be added to the parameters by
  kitchen-qemu  since those are used to communicate with the running qemu instance.

**Comment by trombik** [comment]
You are correct. Hash does not preserve the order of keys nor duplicated keys. Array is the way to go.

>  Should all defaults be disabled when the user specifies some flags or should every default iterate the flags array to see if it has an overriding option?

When I just need to specify `-cpu` and `-machine`, `image` is very convenient.

```yaml
platforms:
  - name: jessie
    driver:
      image: /path/to/image.qcow2
      flags:
        - machine: versatilepb
        - cpu: arm1176
```

When I need complete controls, including disk and bus, it would be nice to be able to disable `image` completely. It is up to the user to provide mandatory disk flags. 

```yaml
platforms:
  - name: jessie
    driver:
      image: null # when the value is null, kitchen-qemu does not add anything other than mon and chardev, and assume the user knows what s/he is doing
      flags:
        - machine: versatilepb
        - cpu: arm1176
        - .... other options including drive ...
```

Or, simply trust the user and do nothing if `image` key does not exist. Personally, I prefer setting "null" explicitly.

There might be cases where one wants to disable or alter even `mon` and `chardev` (I cannot think of any at the moment, though), 

```yaml
platforms:
  - name: jessie
    driver:
      mon: null
      chardev: null
      image: null
      flags:
        - machine: versatilepb
        - cpu: arm1176
        - mon: ....
        - chardev: ....
        - .... other options including drive ...
```

But, as this is the future-that-you-do-NOT-need-at-the-moment, it should be implemented when someone needs it.
